//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.etsoo.CoreFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.etsoo.CoreFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled.
        /// </summary>
        internal static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account expired on {0}.
        /// </summary>
        internal static string AccountExpired {
            get {
                return ResourceManager.GetString("AccountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Expired.
        /// </summary>
        internal static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code function has been temporarily disabled.
        /// </summary>
        internal static string CodeFrozen {
            get {
                return ResourceManager.GetString("CodeFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the code.
        /// </summary>
        internal static string CodeSendingFailed {
            get {
                return ResourceManager.GetString("CodeSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes do not match.
        /// </summary>
        internal static string CodesNoMatch {
            get {
                return ResourceManager.GetString("CodesNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Processing Failed.
        /// </summary>
        internal static string DataProcessingFailed {
            get {
                return ResourceManager.GetString("DataProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection Failed.
        /// </summary>
        internal static string DbConnectionFailed {
            get {
                return ResourceManager.GetString("DbConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Disabled.
        /// </summary>
        internal static string DeviceDisabled {
            get {
                return ResourceManager.GetString("DeviceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device has been temporarily blocked until {0}.
        /// </summary>
        internal static string DeviceFrozen {
            get {
                return ResourceManager.GetString("DeviceFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action.
        /// </summary>
        internal static string InvalidAction {
            get {
                return ResourceManager.GetString("InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not a valid Email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not a valid mobile phone number.
        /// </summary>
        internal static string InvalidMobile {
            get {
                return ResourceManager.GetString("InvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address has been changed.
        /// </summary>
        internal static string IPAddressChanged {
            get {
                return ResourceManager.GetString("IPAddressChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Organization Required.
        /// </summary>
        internal static string JoinOrgRequired {
            get {
                return ResourceManager.GetString("JoinOrgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Action Result.
        /// </summary>
        internal static string NoActionResult {
            get {
                return ResourceManager.GetString("NoActionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Returned.
        /// </summary>
        internal static string NoDataReturned {
            get {
                return ResourceManager.GetString("NoDataReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device Matched.
        /// </summary>
        internal static string NoDeviceMatch {
            get {
                return ResourceManager.GetString("NoDeviceMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed ID does not exist.
        /// </summary>
        internal static string NoId {
            get {
                return ResourceManager.GetString("NoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organization Joined.
        /// </summary>
        internal static string NoOrgJoined {
            get {
                return ResourceManager.GetString("NoOrgJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Password Match.
        /// </summary>
        internal static string NoPasswordMatch {
            get {
                return ResourceManager.GetString("NoPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Agent.
        /// </summary>
        internal static string NoUserAgent {
            get {
                return ResourceManager.GetString("NoUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Found.
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name and password do not match.
        /// </summary>
        internal static string NoUserMatch {
            get {
                return ResourceManager.GetString("NoUserMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid data is passed.
        /// </summary>
        internal static string NoValidData {
            get {
                return ResourceManager.GetString("NoValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization has been disabled.
        /// </summary>
        internal static string OrgDisabled {
            get {
                return ResourceManager.GetString("OrgDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization already exists.
        /// </summary>
        internal static string OrgExists {
            get {
                return ResourceManager.GetString("OrgExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization service expired on {0}.
        /// </summary>
        internal static string OrgExpired {
            get {
                return ResourceManager.GetString("OrgExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Memory.
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your token has expired.
        /// </summary>
        internal static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been temporarily blocked until {0}.
        /// </summary>
        internal static string UserFrozen {
            get {
                return ResourceManager.GetString("UserFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already registered.
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
    }
}
