name: Publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: Build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      # Publish com.etsoo.Utils
      - name: Publish com.etsoo.Utils on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.Utils/com.etsoo.Utils.csproj

          # NuGet package id, used for version detection & defaults to project name
          # PACKAGE_NAME: com.etsoo.Utils

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.Address
      - name: Publish com.etsoo.Address on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.Address/com.etsoo.Address.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.Database
      - name: Publish com.etsoo.Database on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.Database/com.etsoo.Database.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.HtmlUtils
      - name: Publish com.etsoo.HtmlUtils on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.HtmlUtils/com.etsoo.HtmlUtils.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.HTTP
      - name: Publish com.etsoo.HTTP on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.HTTP/com.etsoo.HTTP.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.ImageUtils
      - name: Publish com.etsoo.ImageUtils on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.ImageUtils/com.etsoo.ImageUtils.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.MessageQueue
      - name: Publish com.etsoo.MessageQueue on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.MessageQueue/com.etsoo.MessageQueue.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.SMS
      - name: Publish com.etsoo.SMS on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.SMS/com.etsoo.SMS.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.SMTP
      - name: Publish com.etsoo.SMTP on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.SMTP/com.etsoo.SMTP.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.Localization
      - name: Publish com.etsoo.Localization on version change
        uses: alirezanet/publish-nuget@v3.0.4 # rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.Localization/com.etsoo.Localization.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.SourceGenerators
      - name: Publish com.etsoo.SourceGenerators on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.SourceGenerators/com.etsoo.SourceGenerators.csproj

          # NuGet package id, used for version detection & defaults to project name
          # PACKAGE_NAME: com.etsoo.SourceGenerators

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.CoreFramework
      - name: Publish com.etsoo.CoreFramework on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.CoreFramework/com.etsoo.CoreFramework.csproj

          # NuGet package id, used for version detection & defaults to project name
          # PACKAGE_NAME: com.etsoo.CoreFramework

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.Web
      - name: Publish com.etsoo.Web on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.Web/com.etsoo.Web.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.WebUtils
      - name: Publish com.etsoo.WebUtils on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.WebUtils/com.etsoo.WebUtils.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.DI
      - name: Publish com.etsoo.DI on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.DI/com.etsoo.DI.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}

      # Publish com.etsoo.PureIO
      - name: Publish com.etsoo.PureIO on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.PureIO/com.etsoo.PureIO.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}
